### ISSUE TITLE
doesn't progress, no error.

### ISSUE THREAD

**Issue by splace** [TNTwise/REAL-Video-Enhancer#12]
- [x] I am using the Flatpak 

**Describe the bug**
stops after 3 frames (buffer fills?)

**Screenshots**
![Screenshot from 2024-04-30 16-32-54](https://github.com/TNTwise/REAL-Video-Enhancer/assets/1234848/ce34dcd3-42ea-4986-9837-819097814f16)

**Desktop (please complete the following information):**
 - Fedora silverblue 
 - Current Version: 1.1.2

**GPU**
amd r7 250 - vulkan

**Comment by TNTwise** [comment]
Can you please send a log? It seems like there are too many threads. Try turning down the threading within ncnn settings.

**Comment by splace** [comment]
thanks for the help...

i did that and it now stops at 1.

after reading more i wonder it my software vulkan renderer could be the problem? i can restart with hardware version (this really slows webgl for me.)

**Comment by TNTwise** [comment]
Maybe change the GPU id, it could be defaulting to software vulkan, which in most cases does not work with ncnn vulkan. Try changing GPU id to 1.

**Comment by splace** [comment]
hardware vulkan not helping

happens on all formats

log: (from before any attempt to run, unable to get logs after since have to close app to stop run)

```
ncnn_verson No module named 'torch'
No module named 'cupy'
ERROR: Importing of notifications failed! No module named 'notify'
Program Version: 1.1.2
====================================================================
Model: Rife
added model rife-v4.6
ERROR: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fa7cf1f1fa0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')) Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 61, in create_connection
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 666, in urlopen
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 377, in _make_request
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1001, in _validate_conn
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 314, in connect
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 171, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7fa7cf1f1fa0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 720, in urlopen
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 436, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fa7cf1f1fa0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/REAL-Video-Enhancer-BETA/REAL-Video-Enhancer-BETA/archive-build/REAL-Video-Enhancer/src/programData/checks.py", line 34, in check_if_online
  File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 535, in request
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 648, in send
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fa7cf1f1fa0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fa7cf1f1fa0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
Current sha256 rife: 32b8f3a05e1e8ffb0e3ebab2a0c7e49dfb3c1994378dfe250cd4de2364992e98
New sha256 rife: d87c5acfc1f638a7f1007c8eefd1f2892519ad5177a347e4f700c78eb80cba15
```

**Comment by splace** [comment]
when i try to change download folder i get

`No permissions to write here, please select a different directory.`

**Comment by TNTwise** [comment]
You can view previous logs by going to the second tab in the log window. That will bring up the previous instance.

**Comment by TNTwise** [comment]
> when i try to change download folder i get
> 
> `No permissions to write here, please select a different directory.`

Flatpak is containerized, so you need to allow it access to your download folder.

**Comment by splace** [comment]
OK, never done that and i have 100's apps installed

**Comment by TNTwise** [comment]
Different apps have different permissions set. RVE has the minimum permissions set to run.

**Comment by splace** [comment]
i used flatseal to allow file access, however no change.

**Comment by TNTwise** [comment]
Is there still a rendering issue? That is most likely not a permissions issue. I haven't tested permissions in a while, but there aren't any issues with the defaults.

**Comment by splace** [comment]
> Is there still a rendering issue? That is most likely not a permissions issue. I haven't tested permissions in a while, but there aren't any issues with the defaults.

yes no change, except i can now set output folder.

**Comment by splace** [comment]
here is the end of a previous log, this looks interesting....


```

Standard Error:
[0 llvmpipe (LLVM 17.0.6, 128 bits)]  queueC=0[1]  queueG=0[1]  queueT=0[1]
[0 llvmpipe (LLVM 17.0.6, 128 bits)]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 llvmpipe (LLVM 17.0.6, 128 bits)]  fp16-p/s/a=1/1/0  int8-p/s/a=1/1/1
[0 llvmpipe (LLVM 17.0.6, 128 bits)]  subgroup=4  basic=1  vote=1  ballot=1  shuffle=1
LLVM ERROR: Cannot select: 0x7f7b2c24c0a0: f32,ch = load<(load (s16) from %stack.12
[Errno 2] No such file or directory: '/var/home/simon/.var/app/io.github.tntwise.REAL-Video-Enhancer/renders//CIMG0523.AVI_temp/output_frames/0/' Traceback (most recent call last):
  File "/home/runner/work/REAL-Video-Enhancer-BETA/REAL-Video-Enhancer-BETA/archive-build/REAL-Video-Enhancer/src/runAI/workers.py", line 427, in frameCountThread
FileNotFoundError: [Errno 2] No such file or directory: '/var/home/simon/.var/app/io.github.tntwise.REAL-Video-Enhancer/renders//CIMG0523.AVI_temp/output_frames/0/'

NCNN Preview thread finished

```

**Comment by splace** [comment]
see previous, i switched to hardware.

**Comment by splace** [comment]
i had assumed using a compliment vulkan renderer abstracts away what you use underneath.

**Comment by splace** [comment]
wahoo.. it is now working. turned out the hardware and software vulkan exist together, so i needed to change the gpu reference.
