### ISSUE TITLE
cv2 not functioning properly on Windows 10

### ISSUE THREAD

**Issue by labx12** [TNTwise/REAL-Video-Enhancer#30]
Upon initial setup, I'm getting the following traceback: 
```
Downloading FFMpeg
Downloading: https://github.com/TNTwise/Rife-Vulkan-Models/releases/download/models/ffmpeg.exe
Downloading Python
Downloading: https://github.com/indygreg/python-build-standalone/releases/download/20240814/cpython-3.11.9+20240814-x86_64-pc-windows-msvc-install_only.tar.gz
Extracting: C:\Users\lbend\Documents\INTERP\REAL-Video-Enhancer\python\python.tar.gz
Traceback (most recent call last):
File "C:\Users\lbend\Documents\INTERP\REAL-Video-Enhancer\backend\rve-backend.py", line 5, in <module>
from src.RenderVideo import Render
File "C:\Users\lbend\Documents\INTERP\REAL-Video-Enhancer\backend\src\RenderVideo.py", line 7, in <module>
from .FFmpeg import FFMpegRender
File "C:\Users\lbend\Documents\INTERP\REAL-Video-Enhancer\backend\src\FFmpeg.py", line 1, in <module>
import cv2
ModuleNotFoundError: No module named 'cv2'
invalid syntax (<string>, line 0)
```
have tried uninstalling opencv-python outside of this venv but to no avail
any idea as to how I can fix this?

**Comment by TNTwise** [comment]
Which version are you using?, alpha 3 should be working fine. And that traceback is fine, it does that on purpose to check if dependencies have been installed, it should give a popup to install ncnn, tensorrt, or pytorch

**Comment by labx12** [comment]
hm nevermind - was using alpha 3 w/ the cuda dependencies. seems like it was a bad video causing it to hang as other videos worked fine. closing
