### ISSUE TITLE
[Windows] Upscale with SPAN (Realistic) not starting

### ISSUE THREAD

**Issue by mvigerske** [TNTwise/REAL-Video-Enhancer#35]
Hello, 

I have downloaded the latest Windows version and in the backend the package TensorRT for my Geforce RTX 4060 Ti (16 GB VRAM). (PyTorch Cuda downloads extremely fast, but nothing changes from the options, no Cuda or so) 

The Upscale method Compact works very well, but I wanted to choose one of the SPAN variants. However, these do not start, an error message appears:
`
WARNING:torch_tensorrt.dynamo.conversion.aten_ops_converters:Unable to import quantization op. Please install modelopt library (https://github.com/NVIDIA/TensorRT-Model-Optimizer?tab=readme-ov-file#installation) to add support for compiling quantized models
Using backend: tensorrt
Setting up Upscale
Using device: cuda:0
Traceback (most recent call last):
File "a:\KI\REAL-Video-Enhancer\backend\rve-backend.py", line 235, in <module>
HandleApplication()
File "a:\KI\REAL-Video-Enhancer\backend\rve-backend.py", line 22, in __init__
Render(
File "a:\KI\REAL-Video-Enhancer\backend\src\RenderVideo.py", line 116, in __init__
self.setupUpscale()
File "a:\KI\REAL-Video-Enhancer\backend\src\RenderVideo.py", line 251, in setupUpscale
upscalePytorch = UpscalePytorch(
^^^^^^^^^^^^^^^
File "a:\KI\REAL-Video-Enhancer\python\python\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
return func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "a:\KI\REAL-Video-Enhancer\backend\src\UpscaleTorch.py", line 101, in __init__
self._load()
File "a:\KI\REAL-Video-Enhancer\python\python\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
return func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "a:\KI\REAL-Video-Enhancer\backend\src\UpscaleTorch.py", line 165, in _load
module = torch_tensorrt.compile(
^^^^^^^^^^^^^^^^^^^^^^^
File "a:\KI\REAL-Video-Enhancer\python\python\Lib\site-packages\torch_tensorrt\_compile.py", line 266, in compile
exp_program = dynamo_trace(
^^^^^^^^^^^^^
File "a:\KI\REAL-Video-Enhancer\python\python\Lib\site-packages\torch_tensorrt\dynamo\_tracer.py", line 83, in trace
exp_program = export(
^^^^^^^
File "a:\KI\REAL-Video-Enhancer\python\python\Lib\site-packages\torch\export\__init__.py", line 270, in export
return _export(
^^^^^^^^
File "a:\KI\REAL-Video-Enhancer\python\python\Lib\site-packages\torch\export\_trace.py", line 1017, in wrapper
raise e
File "a:\KI\REAL-Video-Enhancer\python\python\Lib\site-packages\torch\export\_trace.py", line 990, in wrapper
ep = fn(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^
File "a:\KI\REAL-Video-Enhancer\python\python\Lib\site-packages\torch\export\exported_program.py", line 114, in wrapper
return fn(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^
File "a:\KI\REAL-Video-Enhancer\python\python\Lib\site-packages\torch\export\_trace.py", line 1880, in _export
export_artifact = export_func(  # type: ignore[operator]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "a:\KI\REAL-Video-Enhancer\python\python\Lib\site-packages\torch\export\_trace.py", line 1224, in _strict_export
return _strict_export_lower_to_aten_ir(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "a:\KI\REAL-Video-Enhancer\python\python\Lib\site-packages\torch\export\_trace.py", line 1252, in _strict_export_lower_to_aten_ir
gm_torch_level = _export_to_torch_ir(
^^^^^^^^^^^^^^^^^^^^
File "a:\KI\REAL-Video-Enhancer\python\python\Lib\site-packages\torch\export\_trace.py", line 560, in _export_to_torch_ir
gm_torch_level, _ = torch._dynamo.export(
^^^^^^^^^^^^^^^^^^^^^
File "a:\KI\REAL-Video-Enhancer\python\python\Lib\site-packages\torch\_dynamo\eval_frame.py", line 1432, in inner
result_traced = opt_f(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^
File "a:\KI\REAL-Video-Enhancer\python\python\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "a:\KI\REAL-Video-Enhancer\python\python\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
return forward_call(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "a:\KI\REAL-Video-Enhancer\python\python\Lib\site-packages\torch\_dynamo\eval_frame.py", line 465, in _fn
return fn(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^
File "a:\KI\REAL-Video-Enhancer\python\python\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "a:\KI\REAL-Video-Enhancer\python\python\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
return forward_call(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "a:\KI\REAL-Video-Enhancer\python\python\Lib\site-packages\torch\_dynamo\convert_frame.py", line 1269, in __call__
return self._torchdynamo_orig_callable(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "a:\KI\REAL-Video-Enhancer\python\python\Lib\site-packages\torch\_dynamo\convert_frame.py", line 526, in __call__
return _compile(
^^^^^^^^^
File "a:\KI\REAL-Video-Enhancer\python\python\Lib\site-packages\torch\_dynamo\convert_frame.py", line 924, in _compile
guarded_code = compile_inner(code, one_graph, hooks, transform)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "a:\KI\REAL-Video-Enhancer\python\python\Lib\site-packages\torch\_dynamo\convert_frame.py", line 666, in compile_inner
return _compile_inner(code, one_graph, hooks, transform)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "a:\KI\REAL-Video-Enhancer\python\python\Lib\site-packages\torch\_utils_internal.py", line 87, in wrapper_function
return function(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^
File "a:\KI\REAL-Video-Enhancer\python\python\Lib\site-packages\torch\_dynamo\convert_frame.py", line 699, in _compile_inner
out_code = transform_code_object(code, transform)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "a:\KI\REAL-Video-Enhancer\python\python\Lib\site-packages\torch\_dynamo\bytecode_transformation.py", line 1322, in transform_code_object
transformations(instructions, code_options)
File "a:\KI\REAL-Video-Enhancer\python\python\Lib\site-packages\torch\_dynamo\convert_frame.py", line 219, in _fn
return fn(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^
File "a:\KI\REAL-Video-Enhancer\python\python\Lib\site-packages\torch\_dynamo\convert_frame.py", line 634, in transform
tracer.run()
File "a:\KI\REAL-Video-Enhancer\python\python\Lib\site-packages\torch\_dynamo\symbolic_convert.py", line 2796, in run
super().run()
File "a:\KI\REAL-Video-Enhancer\python\python\Lib\site-packages\torch\_dynamo\symbolic_convert.py", line 983, in run
while self.step():
^^^^^^^^^^^
File "a:\KI\REAL-Video-Enhancer\python\python\Lib\site-packages\torch\_dynamo\symbolic_convert.py", line 895, in step
self.dispatch_table[inst.opcode](self, inst)
File "a:\KI\REAL-Video-Enhancer\python\python\Lib\site-packages\torch\_dynamo\symbolic_convert.py", line 1756, in STORE_ATTR
not self.export
AssertionError: Mutating module attribute mean during export.

from user code:
File "a:\KI\REAL-Video-Enhancer\backend\src\spandrel\architectures\SPAN\__arch\span.py", line 286, in forward
self.mean = self.mean.type_as(x)

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information
`
I have carried out the specified installation at https://github.com/NVIDIA/TensorRT-Model-Optimizer?tab=readme-ov-file#installation, but this does not change anything. 

When I set the backend to pytorch, it starts calculating, but the image is totally colourful.

**Comment by patknight** [comment]
Also seen on Manjaro Linux with TensorRT

**Comment by TNTwise** [comment]
Sorry, will investigate when I have time, thank you for reporting

**Comment by patknight** [comment]
Thanks - appreciate the app!

**Comment by TNTwise** [comment]
should be fixed with 2.0.5

**Comment by mvigerske** [comment]
> should be fixed with 2.0.5

it is - thx!
