### ISSUE TITLE
REAL video crash QObject error

### ISSUE THREAD

**Issue by ghost** [TNTwise/REAL-Video-Enhancer#43]
Hello Real Video Enhancer Team

 I'm having a problem with the program,
 I am using the FlatPak version
 I can't use Real Video Enhancer,
 Simply not starting in rendering, Gui does not report any errors, just a time of a few milliseconds that was necsessario to complete the rendering, which is not upheld, not the output file.
 Rounded by the terminal, he found the error, which I do not know the cause (in fact, nor did I understand why this error) in the penultimate line.

 Below the output of my terminal

l**@e**:~$ flatpak run io.github.tntwise.REAL-Video-Enhancer 
Available Backends: ['ncnn']
NCNN Version: 20220729
Half precision support: False
GMFSS support: False

------REAL Video Enhancer------
System Information: 
OS: KDE Flatpak runtime 6.7 x86_64
CPU: Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
GPU: Advanced Micro Devices, Inc. [AMD/ATI] Lexa PRO [Radeon 540/540X/550/550X / RX 540X/550/550X] (rev c7)
RAM: 7.72 GB
Available Disk Space: 3.86GB
-------------------------------------------
Software Information: 
REAL Video Enhancer Version: 2.0
Available Backends: ['ncnn']
NCNN Version: 20220729
Half precision support: False
GMFSS support: False

 
Getting total models, method: Interpolate backend: ncnn
inputVideo: /home/l**/Vídeos/241025220356.mp4
interpolationTimes: 2.0
upscaleTimes: 1
videoFps: 25.0
videoWidth: 444
videoHeight: 250
outputDirectory: /home/l**/Videos
/home/l**/Videos/241025220356_50.0fps_444x250.mkv
inputVideo: /home/l**/Vídeos/241025220356.mp4
interpolationTimes: 2.0
upscaleTimes: 1
videoFps: 25.0
videoWidth: 444
videoHeight: 250
outputDirectory: /home/l**/Videos
/home/l**/Videos/241025220356_50.0fps_444x250.mkv
Traceback (most recent call last):
  File "REAL-Video-Enhancer.py", line 308, in updateVideoGUIDetails
  File "REAL-Video-Enhancer.py", line 291, in setDefaultOutputFile
  File "REAL-Video-Enhancer.py", line 313, in getScale
KeyError: ''
Getting total models, method: Upscale backend: ncnn
inputVideo: /home/l**/Vídeos/241025220356.mp4
interpolationTimes: 1
upscaleTimes: 2
videoFps: 25.0
videoWidth: 444
videoHeight: 250
outputDirectory: /home/l**/Videos
/home/l**/Videos/241025220356_25.0fps_888x500.mkv
inputVideo: /home/l**/Vídeos/241025220356.mp4
interpolationTimes: 1
upscaleTimes: 2
videoFps: 25.0
videoWidth: 444
videoHeight: 250
outputDirectory: /home/l**/Videos
/home/l**/Videos/241025220356_25.0fps_888x500.mkv
inputVideo: /home/l**/Vídeos/241025220356.mp4
interpolationTimes: 1
upscaleTimes: 2
videoFps: 25.0
videoWidth: 444
videoHeight: 250
outputDirectory: /home/l**/Videos
/home/l**/Videos/241025220356_25.0fps_888x500.mkv
Getting total models, method: Upscale backend: ncnn
QObject::setParent: Cannot set parent, new parent is in a different thread
Closed Read Memory

and a screenshot o the program
![Captura de tela de 2024-11-17 14-46-46](https://github.com/user-attachments/assets/df07abb3-2c84-43fb-8af5-c475e80c3b8f)

Sorry for writing errors, I'm using translator, my writing in English is very bad :)

 I thank those who can help me

**Comment by TNTwise** [comment]
Can you try the binary executable from the releases? The flatpak version seems to have issues for many people that I can't replicate. 

This seems to be a temporary solution to fixing flatpak issues:  rm -rf /home/$USER/.var/app/io.github.tntwise.REAL-Video-Enhancer

**Comment by ghost** [comment]
> Can you try the binary executable from the releases? The flatpak version seems to have issues for many people that I can't replicate.
> 
> This seems to be a temporary solution to fixing flatpak issues: rm -rf /home/$USER/.var/app/io.github.tntwise.REAL-Video-Enhancer

I'll try both options, I'll be back to say if it worked

**Comment by TNTwise** [comment]
I was able to reproduce the issue somewhat, hopefully the next stable fixes this issue completely.

**Comment by ghost** [comment]
Yeaah, that's good, I haven't had time to test your suggestions to try to correct the problem that happens to me (I installed on my second PC, I use this PC just for hobby, even make my game Remaster)

and thankyou for attention 

:)

**Comment by TNTwise** [comment]
Closing due to inactivity
