### ISSUE TITLE
(Flatpak) Rife enhancement crashes the application

### ISSUE THREAD

**Issue by Regular-Baf** [TNTwise/REAL-Video-Enhancer#5]
**Describe the bug**
Rife enhancement crashes the application.

**To Reproduce**
Try to use Rife to interpolate the frames of the input video, press start, and it should then crash. 
**Expected behaviour**
The enhancement would complete successfully.

**Logs**
```
ERROR: Importing of notifications failed! module 'notify.linux' has no attribute 'LinuxNotification'
Model: Rife
'MainWindow' object has no attribute 'fps' Traceback (most recent call last):
  File "main.py", line 316, in showChangeInFPS
AttributeError: 'MainWindow' object has no attribute 'fps'

added model rife-v4.6
Program Started
Starting Render, input_file=/run/user/1000/doc/3d9c2c3c/Alice in Wonderland Trailer (180p_30fps_H264-96kbit_AAC).mp4
Start Progressbar/Info Thread
End of start function
INFO: Running AI: ['/home/baf9900/.var/app/io.github.tntwise.REAL-Video-Enhancer/models//rife/rife-ncnn-vulkan', '-m', 'rife-v4.6', '-i', "/home/baf9900/.var/app/io.github.tntwise.REAL-Video-Enhancer/renders//Alice in Wonderland Trailer (180p_30fps_H264-96kbit_AAC).mp4_temp/input_frames/", '-o', "/home/baf9900/.var/app/io.github.tntwise.REAL-Video-Enhancer/renders//Alice in Wonderland Trailer (180p_30fps_H264-96kbit_AAC).mp4_temp/output_frames/0/", '-j', '1:4:2', '-f', '%08d.png', '-n', '2176']
INFO: Starting Render Thread
ERROR: Unhandled exception! [<FrameSummary file /home/runner/work/REAL-Video-Enhancer-BETA/REAL-Video-Enhancer-BETA/archive-build/REAL-Video-Enhancer/src/workers.py, line 383 in finishRenderSetup>, <FrameSummary file /home/runner/work/REAL-Video-Enhancer-BETA/REAL-Video-Enhancer-BETA/archive-build/REAL-Video-Enhancer/src/workers.py, line 415 in Render>, <FrameSummary file /home/runner/work/REAL-Video-Enhancer-BETA/REAL-Video-Enhancer-BETA/archive-build/REAL-Video-Enhancer/src/workers.py, line 229 in optimized_render>, <FrameSummary file /home/runner/work/REAL-Video-Enhancer-BETA/REAL-Video-Enhancer-BETA/archive-build/REAL-Video-Enhancer/src/workers.py, line 213 in render>, <FrameSummary file /usr/lib/python3.8/subprocess.py, line 858 in __init__>, <FrameSummary file /usr/lib/python3.8/subprocess.py, line 1704 in _execute_child>],finishRenderSetup,<class 'FileNotFoundError'>,An unhandled exception occurred: [Errno 2] No such file or directory: '/home/baf9900/.var/app/io.github.tntwise.REAL-Video-Enhancer/models//rife/rife-ncnn-vulkan'

```

**Desktop (please complete the following information):**
 - OS: [Fedora 39]
 - Version [Flatpak]
 
**GPU**
Radeon Vega 64

**Comment by TNTwise** [comment]
Go to settings -> manage models -> and uninstall rife, then reinstall it.

**Comment by Regular-Baf** [comment]
> Go to settings -> manage models -> and uninstall rife, then reinstall it.

It still seems to crash even after reinstalling twice.
```
ERROR: Importing of notifications failed! module 'notify.linux' has no attribute 'LinuxNotification'
Model: Rife
'MainWindow' object has no attribute 'fps' Traceback (most recent call last):
  File "main.py", line 316, in showChangeInFPS
AttributeError: 'MainWindow' object has no attribute 'fps'

added model rife-v4.6
Program Started
{'https://github.com/TNTwise/Rife-Vulkan-Models/releases/download/models/rife-ncnn-vulkan': 'rife-ncnn-vulkan', 'https://github.com/TNTwise/Rife-Vulkan-Models/releases/download/models/rife-v4.6.tar.gz': 'rife-v4.6.tar.gz', 'https://github.com/TNTwise/Rife-Vulkan-Models/releases/download/models/rife-v4.6-ensemble.tar.gz': 'rife-v4.6-ensemble.tar.gz'}
{'https://github.com/TNTwise/Rife-Vulkan-Models/releases/download/models/realesrgan-ncnn-vulkan-20220424-ubuntu.zip': 'realesrgan-ncnn-vulkan-20220424-ubuntu.zip'}
Rife not installed, but tried to remove anyway!
Model: RealESRGAN
Starting Render, input_file=/run/user/1000/doc/3d9c2c3c/Alice in Wonderland Trailer (180p_30fps_H264-96kbit_AAC).mp4
Start Progressbar/Info Thread
End of start function
INFO: Running AI: ['/home/baf9900/.var/app/io.github.tntwise.REAL-Video-Enhancer/models//rife/rife-ncnn-vulkan', '-m', 'rife-v4.6', '-i', "/home/baf9900/.var/app/io.github.tntwise.REAL-Video-Enhancer/renders//Alice in Wonderland Trailer (180p_30fps_H264-96kbit_AAC).mp4_temp/input_frames/", '-o', "/home/baf9900/.var/app/io.github.tntwise.REAL-Video-Enhancer/renders//Alice in Wonderland Trailer (180p_30fps_H264-96kbit_AAC).mp4_temp/output_frames/0/", '-j', '1:4:2', '-f', '%08d.png', '-n', '2176']
INFO: Starting Render Thread
ERROR: Unhandled exception! [<FrameSummary file /home/runner/work/REAL-Video-Enhancer-BETA/REAL-Video-Enhancer-BETA/archive-build/REAL-Video-Enhancer/src/workers.py, line 383 in finishRenderSetup>, <FrameSummary file /home/runner/work/REAL-Video-Enhancer-BETA/REAL-Video-Enhancer-BETA/archive-build/REAL-Video-Enhancer/src/workers.py, line 415 in Render>, <FrameSummary file /home/runner/work/REAL-Video-Enhancer-BETA/REAL-Video-Enhancer-BETA/archive-build/REAL-Video-Enhancer/src/workers.py, line 229 in optimized_render>, <FrameSummary file /home/runner/work/REAL-Video-Enhancer-BETA/REAL-Video-Enhancer-BETA/archive-build/REAL-Video-Enhancer/src/workers.py, line 213 in render>, <FrameSummary file /usr/lib/python3.8/subprocess.py, line 858 in __init__>, <FrameSummary file /usr/lib/python3.8/subprocess.py, line 1704 in _execute_child>],finishRenderSetup,<class 'FileNotFoundError'>,An unhandled exception occurred: [Errno 2] No such file or directory: '/home/baf9900/.var/app/io.github.tntwise.REAL-Video-Enhancer/models//rife/rife-ncnn-vulkan'
```
I've just given it a go on my laptop as well and it's having pretty similar behaviour (intel igpu).

**Comment by TNTwise** [comment]
The binary for rife won't install, im looking at the code and idk how it worked when I tested it. For now, you will need to download the rife binary manually and place it in the folder ~/.var/app/io.github.tntwise.REAL-Video-Enhancer/models/rife/
 
The binary: https://github.com/TNTwise/Rife-Vulkan-Models/releases/download/models/rife-ncnn-vulkan

**Comment by TNTwise** [comment]
Was going to release a new stable soon, and it seems to work fine :\. Cant believe i didnt catch this....

**Comment by Regular-Baf** [comment]
Don't worry about it, thanks for looking into this!
I've given it a go adding the Rife binary into the directory manually, but it's still crashing. I think it may be related to permissions going by the log?
```
ERROR: Importing of notifications failed! module 'notify.linux' has no attribute 'LinuxNotification'
Model: Rife
'MainWindow' object has no attribute 'fps' Traceback (most recent call last):
  File "main.py", line 316, in showChangeInFPS
AttributeError: 'MainWindow' object has no attribute 'fps'

added model rife-v4.6
Program Started
Starting Render, input_file=/run/user/1000/doc/3d9c2c3c/Alice in Wonderland Trailer (180p_30fps_H264-96kbit_AAC).mp4
Start Progressbar/Info Thread
End of start function
INFO: Running AI: ['/home/baf9900/.var/app/io.github.tntwise.REAL-Video-Enhancer/models//rife/rife-ncnn-vulkan', '-m', 'rife-v4.6', '-i', "/home/baf9900/.var/app/io.github.tntwise.REAL-Video-Enhancer/renders//Alice in Wonderland Trailer (180p_30fps_H264-96kbit_AAC).mp4_temp/input_frames/", '-o', "/home/baf9900/.var/app/io.github.tntwise.REAL-Video-Enhancer/renders//Alice in Wonderland Trailer (180p_30fps_H264-96kbit_AAC).mp4_temp/output_frames/0/", '-j', '1:4:2', '-f', '%08d.png', '-n', '2176']
INFO: Starting Render Thread
ERROR: Unhandled exception! [<FrameSummary file /home/runner/work/REAL-Video-Enhancer-BETA/REAL-Video-Enhancer-BETA/archive-build/REAL-Video-Enhancer/src/workers.py, line 383 in finishRenderSetup>, <FrameSummary file /home/runner/work/REAL-Video-Enhancer-BETA/REAL-Video-Enhancer-BETA/archive-build/REAL-Video-Enhancer/src/workers.py, line 415 in Render>, <FrameSummary file /home/runner/work/REAL-Video-Enhancer-BETA/REAL-Video-Enhancer-BETA/archive-build/REAL-Video-Enhancer/src/workers.py, line 229 in optimized_render>, <FrameSummary file /home/runner/work/REAL-Video-Enhancer-BETA/REAL-Video-Enhancer-BETA/archive-build/REAL-Video-Enhancer/src/workers.py, line 213 in render>, <FrameSummary file /usr/lib/python3.8/subprocess.py, line 858 in __init__>, <FrameSummary file /usr/lib/python3.8/subprocess.py, line 1704 in _execute_child>],finishRenderSetup,<class 'PermissionError'>,An unhandled exception occurred: [Errno 13] Permission denied: '/home/baf9900/.var/app/io.github.tntwise.REAL-Video-Enhancer/models//rife/rife-ncnn-vulkan'

```

**Comment by TNTwise** [comment]
You have to give it executable permissions, should be able to right click on the exe, go to properties and make it executable

**Comment by Regular-Baf** [comment]
That was the one, and it's working great now. Thank you so much.

**Comment by TNTwise** [comment]
new release should work now by default
